@id = a55ef8d8-f802-4cbe-8f59-a6934f317158

###
POST http://localhost:3000/api/1.0/kittens HTTP/1.1
Content-Type: application/json

{
    "name": "kitten22",
    "age": 4
}

###
GET http://localhost:3000/api/1.0/kittens HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/api/1.0/kittens/{{id}} HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3000/api/1.0/kittens/{{id}} HTTP/1.1
Content-Type: application/json

{
    "name": "kitten2",
    "age": 14
}

###
DELETE http://localhost:3000/api/1.0/kittens/{{id}} HTTP/1.1
Content-Type: application/json
